# Exercices XP du 23/06/2025
Dernière mise à jour : 7 mars 2025

## Ce que vous apprendrez :
Opérations NumPy de base, y compris la création de tableaux, la manipulation et les opérations de base sur les tableaux.
Compétences dans la manipulation de tableaux unidimensionnels et multidimensionnels.


## Ce que vous allez créer :
Une série de tableaux NumPy démontrant différentes opérations, allant de la simple création de tableaux à des manipulations plus complexes.


## 🌟 Exercice 1 : Création et manipulation de tableaux
Instructions
Créez un tableau NumPy 1D contenant des nombres de 0 à 9.

Résultat attendu :



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np  # Importation de NumPy

In [ ]:
# Étape 1 : Créer un tableau 1D contenant les entiers de 0 à 9
# np.arange génère une séquence de 0 à 9 (10 exclu)
tableau = np.arange(10)

In [ ]:
# Étape 2 : Afficher tableau
print(tableau)  # Résultat : array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[0 1 2 3 4 5 6 7 8 9]


## Exercice 2 : Conversion de type et opérations sur les tableaux
Instructions
Convertissez une liste [3.14, 2.17, 0, 1, 2]en un tableau NumPy et convertissez son type de données en entier.

Résultat attendu :

array([3, 2, 0, 1, 2])

In [ ]:
import numpy as np  # Importer bibliothèque NumPy

In [ ]:
# Étape 1 : Définir liste contenant des nombres flottants
liste = [3.14, 2.17, 0, 1, 2]

In [5]:
# Étape 2 : Conversion de la liste en tableau NumPy avec un type de données entier
# Cela convertit chaque élément en entier en supprimant la partie décimale (pas d'arrondi)
tableau = np.array(liste, dtype=int)

In [ ]:
# Étape 3 : Afficher tableau résultant
print(tableau)  # Résultat : array([3, 2, 0, 1, 2])

[3 2 0 1 2]


## Exercice 3 : Travailler avec des tableaux multidimensionnels
Instructions
Créez un tableau NumPy 3x3 avec des valeurs allant de 1 à 9.

Résultat attendu :



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np  # Importation de la bibliothèque NumPy

In [10]:
# Étape 1 : Générer une séquence de 1 à 9
# np.arange(1, 10) crée un tableau 1D avec les valeurs de 1 à 9
valeurs = np.arange(1, 10)

In [11]:
# Étape 2 : Remodeler le tableau en 3 lignes et 3 colonnes (3x3)
# reshape transforme le tableau 1D en matrice 2D
tableau_3x3 = valeurs.reshape((3, 3))

In [12]:
# Étape 3 : Affichage du tableau 2D
print(tableau_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercice 4 : Création d'un tableau multidimensionnel avec des nombres aléatoires
Instructions
Créez un tableau NumPy 2D de forme (4, 5) rempli de nombres aléatoires.

Résultat attendu :

array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [ ]:
import numpy as np  # Importation de NumPy

In [13]:
# Étape 1 : Créer un tableau 2D de forme (4, 5) avec des valeurs aléatoires entre 0 et 1
# np.random.rand(4, 5) génère un tableau 4x5 de flottants aléatoires uniformes
tableau_aleatoire = np.random.rand(4, 5)

In [23]:
# Étape 2 : Arrondir les valeurs à 2 décimales pour lisibilité (optionnel)
tableau_aleatoire = np.round(tableau_aleatoire, 2)

In [24]:
# Étape 3 : Affichage du tableau
print(tableau_aleatoire)

[[0.81 0.58 0.03 0.21 0.14]
 [0.9  0.6  0.38 0.6  0.6 ]
 [0.29 0.34 0.23 0.32 0.12]
 [0.31 0.8  0.09 0.93 0.61]]


## 🌟 Exercice 5 : Indexation des tableaux
Instructions
Sélectionnez la deuxième ligne d’un tableau NumPy 2D donné.

Résultat attendu :



array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [ ]:
import numpy as np  # Importation de NumPy

In [25]:
# Étape 1 : Définir le tableau 2D
array = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])

In [26]:
# Étape 2 : Sélection de la deuxième ligne (index 1, car l’indexation commence à 0)
deuxieme_ligne = array[1]

In [27]:
# Étape 3 : Affichage de la ligne extraite
print(deuxieme_ligne)

[20 21 22 23 24]


## 🌟 Exercice 6 : Inversion des éléments
Instructions
Inverse l'ordre des éléments dans un tableau NumPy 1D donné (le premier élément devient le dernier).

Résultat attendu :



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
import numpy as np  # Importation de NumPy

In [29]:
# Étape 1 : Création du tableau initial de 0 à 9
tableau = np.arange(10)

In [30]:
# Étape 2 : Inversion de l'ordre des éléments avec slicing
tableau_inverse = tableau[::-1]

In [31]:
# Étape 3 : Affichage du tableau inversé
print(tableau_inverse)

[9 8 7 6 5 4 3 2 1 0]


## 🌟 Exercice 7 : Matrice d'identité
Instructions
Créez une matrice d'identité 4x4 à l'aide de NumPy.

Résultat attendu :



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
import numpy as np  # Importation de NumPy

In [33]:
# Étape 1 : Création d'une matrice identité de taille 4x4
# np.eye(n) génère une matrice identité de taille n
matrice_identite = np.eye(4)

In [34]:
# Étape 2 : Affichage de la matrice
print(matrice_identite)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 🌟 Exercice 8 : Fonctions d'agrégation simples
Instructions
Trouvez la somme et la moyenne d'un tableau 1D donné.

Résultat attendu :



Sum: 45, Average: 4.5

In [35]:
import numpy as np  # Importation de NumPy

In [36]:
# Étape 1 : Création du tableau 1D
tableau = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# Étape 2 : Calcul de la somme des éléments
somme = np.sum(tableau)

In [38]:
# Étape 3 : Calcul de la moyenne des éléments
moyenne = np.mean(tableau)

In [39]:
# Étape 4 : Affichage des résultats
print("Sum:", somme, ", Average:", moyenne)

Sum: 45 , Average: 4.5


## Exercice 9 : Créer un tableau et modifier sa structure
Instructions
Créez un tableau NumPy avec des éléments de 1 à 20 ; puis remodelez-le en une matrice 4x5.

Résultat attendu :



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


In [40]:
import numpy as np  # Importation de NumPy

In [41]:
# Étape 1 : Créer un tableau contenant les entiers de 1 à 20
tableau = np.arange(1, 21)

In [42]:
# Étape 2 : Remodeler le tableau en matrice 4x5
matrice = tableau.reshape((4, 5))

In [43]:
# Étape 3 : Affichage de la matrice résultante
print(matrice)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## 🌟 Exercice 10 : Sélection conditionnelle de valeurs
Instructions
Extraire tous les nombres impairs d'un tableau NumPy donné.

Résultat attendu :



array([1, 3, 5, 7, 9])

In [44]:
import numpy as np  # Importation de NumPy

In [45]:
# Étape 1 : Créer un tableau 1D de 0 à 9
tableau = np.arange(10)

In [46]:
# Étape 2 : Sélectionner les éléments impairs avec une condition
# Un nombre est impair si le reste de la division par 2 est 1
impairs = tableau[tableau % 2 == 1]

In [47]:
# Étape 3 : Affichage du résultat
print(impairs)

[1 3 5 7 9]
