# Exercices XP Ninja
Dernière mise à jour : 20 novembre 2024

👩‍🏫 👩🏿‍🏫 Ce que vous apprendrez
Comment manipuler des matrices et trouver des points communs dans des ensembles de données à l'aide de NumPy.
Opérations de tableau avancées telles que le remplacement de la valeur maximale et l'identification de la valeur commune.


🛠️ Ce que vous allez créer
Un ensemble d'exercices stimulants qui incluent le remplacement de la valeur maximale dans une matrice et la recherche de valeurs communes entre les tableaux.

## Exercice 1 : Remplacement de la valeur maximale dans une matrice
Instructions
Créez une matrice aléatoire 5x5 et remplacez la valeur maximale par 0.

Résultat attendu :



array([[0.23, 0.35, 0.01, 0.05, 0.11],
       [0.91, 0.28, 0.66, 0.13, 0.14],
       [0.94, 0.40, 0.76, 0.65, 0.46],
       [0.12, 0.15, 0.95, 0.57, 0.60],
       [0.17, 0.97, 0.87, 0.45, 0.  ]])

In [1]:
import numpy as np  # Import de NumPy

In [2]:
# Étape 1 : Créer une matrice 5x5 avec des valeurs aléatoires entre 0 et 1
matrice = np.random.rand(5, 5)

In [3]:
# Étape 2 : Trouver la valeur maximale dans la matrice
valeur_max = np.max(matrice)

In [5]:
# Étape 3 : Trouver l’indice (position) de la valeur maximale
indice_max = np.unravel_index(np.argmax(matrice), matrice.shape)

In [6]:
# Étape 4 : Remplacer la valeur maximale par 0
matrice[indice_max] = 0

In [7]:
# Étape 5 : Afficher la matrice modifiée
print(np.round(matrice, 2))

[[0.22 0.   0.57 0.44 0.23]
 [0.84 0.12 0.39 0.03 0.41]
 [0.42 0.35 0.89 0.74 0.19]
 [0.11 0.8  0.21 0.18 0.67]
 [0.84 0.78 0.34 0.38 0.38]]


## Exercice 2 : Recherche de valeurs communes dans des tableaux
Instructions
Trouvez les valeurs communes entre deux tableaux aléatoires de taille 5.

Résultat attendu :



array([0.35, 0.66, 0.76])


In [27]:
import numpy as np  # Import de NumPy

In [28]:
# Étape 1 : Créer deux tableaux aléatoires de taille 5 avec valeurs arrondies
a = np.round(np.random.rand(5), 2)
b = np.round(np.random.rand(5), 2)

In [29]:
# Étape 2 : Trouver les valeurs communes avec np.intersect1d
valeurs_communes = np.intersect1d(a, b)

In [30]:
# Étape 3 : Afficher les tableaux et leurs valeurs communes
print("Tableau A:", a)
print("Tableau B:", b)
print("Valeurs communes:", valeurs_communes)

Tableau A: [0.13 0.68 0.15 0.22 0.48]
Tableau B: [0.81 0.13 0.12 0.57 0.27]
Valeurs communes: [0.13]


## Exercice 4 : Détermination du rang de la matrice
Instructions
Générez une matrice aléatoire 4x4 et trouvez le rang de la matrice.

Résultat attendu :



Rank: 4


In [31]:
import numpy as np  # Import de NumPy

In [32]:
# Étape 1 : Générer une matrice 4x4 avec des valeurs aléatoires
matrice = np.random.rand(4, 4)

In [33]:
# Étape 2 : Calculer le rang de la matrice
rang = np.linalg.matrix_rank(matrice)

In [34]:
# Étape 3 : Afficher le rang
print("Rank:", rang)

Rank: 4


## Exercice 5 : Création d'un tableau de bordures
Instructions
Créez un tableau 2D avec 1 sur la bordure et 0 à l'intérieur.

Résultat attendu :



array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [35]:
import numpy as np  # Import de NumPy

In [36]:
# Étape 1 : Créer un tableau 5x5 rempli de 1
tableau = np.ones((5, 5), dtype=int)

In [37]:
# Étape 2 : Remplir l'intérieur (éléments non bordure) avec des 0
tableau[1:-1, 1:-1] = 0

In [38]:
# Étape 3 : Afficher le tableau résultant
print(tableau)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
